version: 2.1

parameters:
  dev-orb-version:
    type: string
    default: "dev:testing"
  run-integration-tests:
    type: boolean
    default: false

orbs:
  brew: hubci/homebrew@<<pipeline.parameters.dev-orb-version>>
  orb-tools: circleci/orb-tools@10.0

workflows:
  main:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint
      - orb-tools/publish-dev:
          orb-name: hubci/homebrew
          alpha-version-ref: "dev:testing"
          checkout: true
          attach-workspace: false
          orb-path: orb.yml
          requires:
            - orb-tools/lint
          context: orbs
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          context: orbs
          requires:
            - orb-tools/publish-dev
  integration-test_deploy:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      - integration-test-editing
      - brew/update-tap:
          tap-url: "https://github.com/pungi-org/homebrew-tap.git"
          formula-name: pungi
          target-url: "https://github.com/pungi-org/pungi"
          github-token: "blah"
          test: true
          pre-steps:
            - run: echo "export CIRCLE_TAG=v0.1.0" >> $BASH_ENV
      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: hubci/homebrew
          add-pr-comment: true
          fail-if-semver-not-indicated: true
          publish-version-tag: true
          requires:
            - integration-test-editing
          filters:
            branches:
              only: trunk
          context:
            - orbs

jobs:
  integration-test-editing:
    docker:
      - image: cimg/base:2021.07
    steps:
      - run:
          name: "Try running"
          command: echo "hi"
